---
- name: Cloudformation Playbook
  hosts: local
  connection: local
  gather_facts: yes
  vars_files:
    - vars/cloudfront_security_groups.var.yml
  pre_tasks:

    - name: Obtain list of AWS IPs
      uri:
        url: https://ip-ranges.amazonaws.com/ip-ranges.json
        method: GET
        force: yes
      register: aws_ips

    - name: Convert list of AWS Ips to json object
      set_fact:
        aws_ipv4_json: "{{ aws_ips.json.prefixes | selectattr('service', 'equalto', 'CLOUDFRONT') | list }}"
        aws_ipv6_json: "{{ aws_ips.json.ipv6_prefixes | selectattr('service', 'equalto', 'CLOUDFRONT') | list }} "

    - name: Convert list of AWS Ips to json object
      set_fact:
        cloudfront_ips: "{{ aws_ipv4_json + aws_ipv6_json }}"

# Change me if we have a default limit 60.
# * Do note that max 1000 entries can only be attached to an ENI and anything above 200 in a SG drops max SG attachments
    - name: Set maximum entries per split
      set_fact:
        max_entries_per_split: 150
        total_entries: "{{ cloudfront_ips | length}}"

    - name: Calculate total splits
      set_fact:
        total_splits: "{{ ((total_entries |int - 1) // max_entries_per_split) + 1 }}"

    - name: Compile Jinja2 Security Group template
      template:
        src: cloudfront_security_groups.cfn.yml.j2
        dest: templates/cloudfront_security_groups.cfn.yml

  roles:
    - ansible_cloudformation
